# Generated by Django 3.2.7 on 2021-11-12 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqtp', '0006_auto_20211111_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('path', models.CharField(max_length=500, verbose_name='报告路径')),
                ('detail', models.TextField(verbose_name='报告详情')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='sqtp.plan')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
