# NOTE: Generated By HttpRunner v3.1.6
# FROM: day1\demo2_case.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from day1.demo1_login_list_test import TestCaseDemo1LoginList as Demo1LoginList


class TestCaseDemo2Case(HttpRunner):

    config = Config("引用测试").base_url("http://localhost")

    teststeps = [
        Step(RunTestCase("引用demo1").call(Demo1LoginList).export(*["cookie"])),
        Step(
            RunRequest("setp2_list_course")
            .get("/api/mgr/sq_mgr/")
            .with_params(**{"action": "list_course", "pagenum": 1, "pagesize": 20})
            .with_cookies(**{"sessionid": "$cookie"})
            .extract()
            .with_jmespath("body.total", "total")
            .with_jmespath("body.retcode", "retcode")
            .validate()
            .assert_equal("$total", 2)
            .assert_equal("$retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo2Case().test_start()
