# NOTE: Generated By HttpRunner v3.1.6
# FROM: day1\demo1_login_list.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemo1LoginList(HttpRunner):

    config = (
        Config("case001_login")
        .variables(**{"username": "auto"})
        .base_url("http://localhost")
        .export(*["cookie"])
    )

    teststeps = [
        Step(
            RunRequest("step1_login_request")
            .post("/api/mgr/loginReq")
            .with_data({"username": "auto", "password": "sdfsdfsdf"})
            .extract()
            .with_jmespath("body.retcode", "retcode")
            .with_jmespath("cookies.sessionid", "cookie")
            .validate()
            .assert_equal("$retcode", 0)
        ),
        Step(
            RunRequest("setp2_list_course")
            .get("/api/mgr/sq_mgr/")
            .with_params(**{"action": "list_course", "pagenum": 1, "pagesize": 20})
            .with_cookies(**{"sessionid": "$cookie"})
            .extract()
            .with_jmespath("body.total", "total")
            .with_jmespath("body.retcode", "retcode")
            .validate()
            .assert_equal("$total", 2)
            .assert_equal("$retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo1LoginList().test_start()
