# Generated by Django 3.2.7 on 2021-11-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqtp', '0005_config_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['id', 'sorted_no'], 'verbose_name': '测试步骤表'},
        ),
        migrations.AddField(
            model_name='step',
            name='sorted_no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='步骤顺序'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=128, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='request',
            name='step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to='sqtp.step'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('belong_case', 'sorted_no')},
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(0, '未运行'), (1, '执行中'), (2, '中断'), (3, '已执行')], default=0, verbose_name='执行状态')),
                ('exec_counts', models.PositiveSmallIntegerField(default=0, verbose_name='执行次数')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='计划名称')),
                ('cases', models.ManyToManyField(blank=True, to='sqtp.Case', verbose_name='测试用例')),
                ('create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_create_by', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sqtp.environment', verbose_name='测试环境')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
