# Generated by Django 3.2.7 on 2021-10-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0002_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_sgin',
            field=models.BooleanField(default=False),
        ),
    ]
