# Generated by Django 3.2.7 on 2021-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0003_guest_is_sgin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(to='sgin.Event'),
        ),
    ]
