# Generated by Django 3.2.7 on 2021-10-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0004_auto_20211014_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='is_sgin',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='join_time',
        ),
        migrations.CreateModel(
            name='GuestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('is_sgin', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgin.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgin.guest')),
            ],
        ),
    ]
