# Generated by Django 3.2.7 on 2021-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0005_auto_20211014_2137'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='GuestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('is_sgin', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=models.deletion.CASCADE, to='sgin.event', verbose_name='发布会')),
                ('guest', models.ForeignKey(on_delete=models.deletion.CASCADE, to='sgin.guest', verbose_name='嘉宾')),
            ],
            options={
                'db_table': 'sgin_guest_events',
            },
        ),
        migrations.AlterField(
            model_name='guest',
            name='events',
            field=models.ManyToManyField(through='sgin.GuestEvent', to='sgin.Event'),
        ),
        #指定修改的数据库
        migrations.AlterModelTable(
            name='GuestEvent',  # 中间表的模型名
            table='sgin_guest_events'  # 当前数据库中的中间表名
        )
    ]
    # 重新定义数据库操作
    operations = [
        #分离数据库状态
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        # 新增join_time字段
        migrations.AddField(
            model_name='GuestEvent',
            name='join_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        # 新增is_sgin字段
        migrations.AddField(
            model_name='GuestEvent',
            name='is_sgin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='GuestEvent',
            #不创建实际的表
            table=None,
        ),
    ]
