# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase\测开3期_PlanCase2.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase测开3期Plancase2(HttpRunner):

    config = Config("PlanCase2").base_url("http://localhost")

    teststeps = [
        Step(RunRequest("step_name").get("/demo/path")),
    ]


if __name__ == "__main__":
    TestCase测开3期Plancase2().test_start()
