# Generated by Django 3.2.7 on 2021-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('limits', models.IntegerField(default=100)),
                ('status', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
