# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase\测试开发3_case001.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase测试开发3Case001(HttpRunner):

    config = Config("case003").base_url("http://localhost")

    teststeps = [
        Step(RunRequest("step_name").get("/demo/path")),
    ]


if __name__ == "__main__":
    TestCase测试开发3Case001().test_start()
