# Generated by Django 3.2.7 on 2021-11-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqtp', '0004_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sqtp.project'),
        ),
    ]
