# Generated by Django 3.2.7 on 2021-10-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='demo_case.json', max_length=1000, verbose_name='用例文件路径')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='名称')),
                ('base_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='IP/域名')),
                ('variables', models.JSONField(null=True, verbose_name='变量')),
                ('parameters', models.JSONField(null=True, verbose_name='参数')),
                ('export', models.JSONField(null=True, verbose_name='用例返回值')),
                ('verify', models.BooleanField(default=False, verbose_name='https校验')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('variables', models.JSONField(null=True, verbose_name='变量')),
                ('extract', models.JSONField(null=True, verbose_name='请求返回值')),
                ('validate', models.JSONField(null=True, verbose_name='校验项')),
                ('setup_hooks', models.JSONField(null=True, verbose_name='初始化')),
                ('teardown_hooks', models.JSONField(null=True, verbose_name='清除')),
                ('belong_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teststeps', to='sqtp.case')),
                ('linked_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_steps', to='sqtp.case')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.SmallIntegerField(choices=[(0, 'GET'), (1, 'POST'), (2, 'PUT'), (3, 'DELETE')], default=0, verbose_name='请求方法')),
                ('url', models.CharField(default='/', max_length=1000, verbose_name='请求路径')),
                ('params', models.JSONField(null=True, verbose_name='url参数')),
                ('headers', models.JSONField(null=True, verbose_name='请求头')),
                ('cookies', models.JSONField(null=True, verbose_name='Cookies')),
                ('data', models.JSONField(null=True, verbose_name='表单参数')),
                ('json', models.JSONField(null=True, verbose_name='json参数')),
                ('step', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sqtp.step')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sqtp.config'),
        ),
    ]
