# NOTE: Generated By HttpRunner v3.1.6
# FROM: day2\demo1_add_course.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from day2.login_case_test import TestCaseLoginCase as LoginCase


class TestCaseDemo1AddCourse(HttpRunner):

    config = (
        Config("增加课程").base_url("${ENV(base_url)}").export(*["course_id", "cookie"])
    )

    teststeps = [
        Step(RunTestCase("登录").call(LoginCase).export(*["cookie"])),
        Step(
            RunRequest("发送增加课程请求")
            .with_variables(**{"name": "小学语文", "desc": "语文课", "idx": 3})
            .setup_hook("${before_add_course($request)}")
            .post("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "$cookie"})
            .with_data(
                {
                    "action": "add_course",
                    "data": {"name": "$name", "desc": "$desc", "display_idx": "$idx"},
                }
            )
            .teardown_hook("${after_add_course($response)}")
            .extract()
            .with_jmespath("body.id", "course_id")
            .validate()
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo1AddCourse().test_start()
