# NOTE: Generated By HttpRunner v3.1.6
# FROM: day2\demo3_delete_course.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from day2.demo2_update_course_test import TestCaseDemo2UpdateCourse as Demo2UpdateCourse


class TestCaseDemo3DeleteCourse(HttpRunner):

    config = Config("删除课程").base_url("http://localhost")

    teststeps = [
        Step(
            RunTestCase("登录、添加课程并修改")
            .call(Demo2UpdateCourse)
            .export(*["cookie", "course_id"])
        ),
        Step(
            RunRequest("删除课程请求")
            .delete("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "$cookie"})
            .with_data({"action": "delete_course", "id": "$course_id"})
            .validate()
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo3DeleteCourse().test_start()
