# NOTE: Generated By HttpRunner v3.1.6
# FROM: day2\demo2_update_course.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from day2.demo1_add_course_test import TestCaseDemo1AddCourse as Demo1AddCourse


class TestCaseDemo2UpdateCourse(HttpRunner):

    config = (
        Config("修改课程").base_url("http://localhost").export(*["course_id", "cookie"])
    )

    teststeps = [
        Step(
            RunTestCase("登录并添加课程").call(Demo1AddCourse).export(*["cookie", "course_id"])
        ),
        Step(
            RunRequest("修改课程")
            .put("/api/mgr/sq_mgr/")
            .with_cookies(**{"sessionid": "$cookie"})
            .with_data(
                {
                    "action": "modify_course",
                    "id": "$course_id",
                    "newdata": '{"name":"python教学","desc":"测试开发课程", "display_idx":"1"}',
                }
            )
            .validate()
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo2UpdateCourse().test_start()
