# NOTE: Generated By HttpRunner v3.1.6
# FROM: day2\login_case.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginCase(HttpRunner):

    config = (
        Config("login_demo")
        .variables(**{"account": "auto", "psw": "sdfsdfsdf", "code": 0})
        .base_url("http://localhost")
        .export(*["cookie"])
    )

    teststeps = [
        Step(
            RunRequest("登录")
            .post("/api/mgr/loginReq")
            .with_data({"username": "$account", "password": "$psw"})
            .extract()
            .with_jmespath("body.retcode", "retcode")
            .with_jmespath("cookies.sessionid", "cookie")
            .validate()
            .assert_equal("$retcode", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginCase().test_start()
