# NOTE: Generated By HttpRunner v3.1.6
# FROM: day2\setup_demo.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSetupDemo(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"account-psw-code": [["auto", "sdfsdfsdf", 0]]})
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("caseoo1").base_url("http://localhost").export(*["cookie"])

    teststeps = [
        Step(
            RunRequest("登录")
            .setup_hook("${hook_setup()}")
            .post("/api/mgr/loginReq")
            .with_data({"username": "$account", "password": "$psw"})
            .teardown_hook("${hook_teardown()}")
            .extract()
            .with_jmespath("body.retcode", "retcode")
            .with_jmespath("cookies.sessionid", "cookie")
            .validate()
            .assert_equal("$retcode", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseSetupDemo().test_start()
