# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase\测开3期_case001.json


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCase测开3期Case001(HttpRunner):

    config = Config("case004").base_url("http://localhost")

    teststeps = [
        Step(RunRequest("step_name").get("/demo/path")),
    ]


if __name__ == "__main__":
    TestCase测开3期Case001().test_start()
